services:
  database:
    image: 'postgres:latest'
    ports:
      - '5430:5432'
    environment:
      - 'POSTGRES_USER=filipeDevs'
      - 'POSTGRES_DB=filipeDevs'
      - 'POSTGRES_PASSWORD=filipeDevs'
    volumes:
      - '~/volumes/filipeDevs/postgres:/var/lib/postgresql/data'